theme = "tokyonight_storm"

[editor] 
auto-format = false
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = false
ignore = false
git-ignore = false
git-global = false
git-exclude = false

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true



[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "."
nbsp = "⍽"
tab = "-"
newline = "⏎"
#tabpad = "."

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
