
[[language]]
name = "rust"
language-id = "rust"
language-servers = [ "rust-analyzer" ]
scope = "source.rust"
file-types = ["rs"]
roots = ["Cargo.lock", "Cargo.toml"]

[[langugae]]
name = "cpp"
language-id = "cpp"
scope = "sources.cpp"
file-types = ["cpp", "cc", "hpp", "h"]

[[langugae]]
name = "html"
language-id = "html"
language-servers = ["vscode-html-language-server"]

[[language]]
name = "css"
language-id = "css"
language-servers = ["vscode-css-language-server"]

[[language]]
name = "typescript"
language-id = "typescript"
language-servers = [ "typescript-language-server" ]
scope = "sources.typescript"
file-types = ["ts", "tsx"]
roots = ["package.json"]
auto-format = true

[[language]]
name = "tsx"
language-id = "tsx"
file-types = ["tsx"]

[[language]]
name = "graphql"
language-id = "graphql"
language-servers = ["graphql-lsp"]
file-types = ["graphql", "graphqls", "gql", "gqls"]

[[language]]
name = "haskell"
scope = "source.haskell"
language-servers = [ "haskell-language-server" ]
file-types = ["hs"]
auto-format = true

[[langauge]]
name = "php"
scope = "sources.php"
language-servers = [ "intelephense" ]
file-types = "php"
auto-format = true
